org: rikbignell
app: serverless-footyapp
service: serverless-footyapp
frameworkVersion: '3'

custom:
  playertableName: 'player_table'
  resultstableName: 'results_table'
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ PlayerTable, Arn ]
            - Fn::GetAtt: [ ResultsTable, Arn ]
  environment:
    PLAYER_TABLE: ${self:custom.playertableName}
    RESULTS_TABLE: ${self:custom.resultstableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    PlayerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: Name
            AttributeType: S
        KeySchema:
          - AttributeName: Name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1
        TableName: ${self:custom.playertableName}
    ResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
        KeySchema:
          - AttributeName: Date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1
        TableName: ${self:custom.resultstableName}